// Code generated by mockery v2.9.4. DO NOT EDIT.

package main

import mock "github.com/stretchr/testify/mock"

// MockRandom is an autogenerated mock type for the Random type
type MockRandom struct {
	mock.Mock
}

// GetRandomNum provides a mock function with given fields:
func (_m *MockRandom) GetRandomNum() (int, error) {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
