version: '3.5'
networks:
  default:
    name: go-test-kit

services:
  randomnumber:
    build: 
      context: ..
      dockerfile: ./Dockerfile
    env_file:
      - ./config.env
    ports:
      - "8080:8080"

  acceptance-tester:
    image: golang:1.16
    depends_on:
      - randomnumber
    restart: 'no'
    environment:
      - ACCEPTANCE_NETWORK=go-test-kit
    env_file:
      - ./config.env
    working_dir: /acceptance
    expose:
      - "5028"
    ports:
      - "5028:5028"
    volumes:
      - .:/acceptance
      - ${GOPATH:-~/go}/pkg:/go/pkg
      - /var/run/docker.sock:/var/run/docker.sock
    command: bash -c "go test -parallel 1 -v ."
